### ISSUE TITLE
Interface: Is the Discovery interface on mobile devices obscuring the key functions of the application?

### ISSUE THREAD

**Issue by grange85** [nationalarchives/findability#1]
Identify anything

**Comment by cariannewhitworth** [comment]
Does the logo/menu button/breadcrumb and discovery help/send us feedback copy need to be so prevalent? And is it even consistent across Discovery (ie. if we wanted to change it, how could we make sure it changes across everything)

**Comment by cariannewhitworth** [comment]
Just adding a note from yesterday's meeting that a good task could be for us to identify the TOP 3 or 5 things a user needs when they hit each stage of the information finding process (search, results, browse, details page etc) and then do a quick check - what are the 3 or 5 things that users are currently seeing first?

**Comment by catherinelliott** [comment]
Have you guys looked at how much usage of Discovery is on mobile devices and how that's changing over time? Be good to get a relatively simple understanding of usage on mobile vs usage on large screen.  % split, change over time, av. length of visit, pages visited etc.  This will help us understand the impact of the poor experience and be a baseline for measuring against when improvements are made.

**Comment by catherinelliott** [comment]
Determining how success will be measured (KPIs) and etablishing a baseline obviously applies for all workstreams within Findability  as you've indicated in one of the other issues.

**Comment by grange85** [comment]
Thanks @ManassehBBTNA - this is really good. I've taken the top outcome into it's own issues and we can follow up there.
Discovery menu #14 

I think the second outcome overlaps with what @sarrahdi and @jklepfer are looking at?
