### ISSUE TITLE
SEO: Improve standard metadata in all items in the series WO 372 and PROB 11

### ISSUE THREAD

**Issue by grange85** [nationalarchives/findability#12]
- [ ] Confirm the appropriate `<title>` 
- [ ] Confirm the appropriate `<meta name="description">` 
- [ ] Confirm the appropriate `<meta name="keywords">`
- [ ] Apply tags to all items in WO 372 and PROB 11
- [ ] Confirm with .NET designers if their time and/or input is required?
- [ ] Deploy to TEST
- [ ] Deploy to LIVE

**Comment by netdesignr** [comment]
**Meta tags for WO 372**

Existing meta:
![existing-meta](https://user-images.githubusercontent.com/5245264/44781184-98578600-ab7b-11e8-9385-298edfd4dd83.png)

Updated meta:
![updated-meta](https://user-images.githubusercontent.com/5245264/44781165-8d9cf100-ab7b-11e8-9641-6b7bed31d4b9.png)

**Title:**
`<title>Public record | Medal card of Owen, Wilfred E S | The National Archives</title>`

**Description:**
`<meta name="description" content="Download public record Medal card of Owen, 
Wilfred E S. WO 372, Lieutenant, Manchester Regiment, 1914-1920. The official archive of the UK government, The National Archives">`

**Keywords:** ( Google does not use the keywords meta tag in web ranking so not quite sure if we still want to keep it ? )
`<meta name="keywords" content="official archives of the uk, public record, download public record, medal card, Owen, Wilfred E S, ">`

**Comment by grange85** [comment]
@netdesignr I think we should probably leave off keywords for now - unless there's a reason for it - e.g. if we decided to make use of them for internal search? But I guess we can "turn them on" if we need to in the future?

**Comment by netdesignr** [comment]
**Meta tags for WO 372**
URL: http://discovery.nationalarchives.gov.uk/details/r/D744951

Existing meta:
![existing-meta](https://user-images.githubusercontent.com/5245264/44781184-98578600-ab7b-11e8-9385-298edfd4dd83.png)

Updated meta:
![updated-meta](https://user-images.githubusercontent.com/5245264/44781165-8d9cf100-ab7b-11e8-9641-6b7bed31d4b9.png)

**Title:**
`<title>Public record | Medal card of Owen, Wilfred E S | The National Archives</title>`

**Description:**
`<meta name="description" content="Download public record Medal card of Owen, 
Wilfred E S. WO 372, Lieutenant, Manchester Regiment, 1914-1920. The official archive of the UK government, The National Archives">`

**Keywords:** ( Google does not use the keywords meta tag in web ranking so not quite sure if we still want to keep it ? )
`<meta name="keywords" content="official archives of the uk, public record, download public record, medal card, Owen, Wilfred E S, ">`

**Comment by netdesignr** [comment]
The difference between a ranked page in google and a non ranked one. 

**Page: WO 372**
URL: http://discovery.nationalarchives.gov.uk/details/r/D744951
![wo372](https://user-images.githubusercontent.com/5245264/44918077-03e35400-ad32-11e8-92ee-ce9c1f6302f9.png)

**Page: Public records act**
URL: http://www.nationalarchives.gov.uk/information-management/legislation/public-records-act/
![public-record](https://user-images.githubusercontent.com/5245264/44918210-51f85780-ad32-11e8-9e36-d9787935e0fd.jpg)
