### ISSUE TITLE
Replace menu/header on Discovery with the one used for www

### ISSUE THREAD

**Issue by grange85** [nationalarchives/findability#14]
- [x] Andy to talk to Andrew about timescales as this is stuck behind Discovery 6 release
- [x] Confirm that this has been tested fully across Discovery
- [x] Identify and log where this ISN'T going (e.g. sso, advance and bulk orders??)

## Outcome of sprint 1
Replacing the existing mobile banner with the one used on www will offer consistency and make the site more compact.

So, from this:
![image](https://user-images.githubusercontent.com/783875/45040821-cac32080-b05e-11e8-9d69-908eaf69aadc.png)

To (something like) this:
![image](https://user-images.githubusercontent.com/783875/45040864-df071d80-b05e-11e8-90fb-dc9d70b3587f.png)

**Comment by hoake** [comment]
To help prioritise where to start implementing the menu/header across Discovery services

Most viewed areas of Discovery on a mobile device (including tablets)
--

rank | Content group | URL | Page   views
-- | -- | -- | --
1 | Search results | /results/r | 59485
2 | View records of other archives | /details/r | 24577
3 | View TNA record description | /details/r | 24496
4 | Discovery home | / | 11951
5 | View repository details | /details/a | 10313
6 | View creators record description | /details/c | 10164
7 | View TNA download record description | /details/r | 9973
8 | Advanced search results | /results/r | 5626
9 | Advanced search | /advanced-search/ | 3850
10 | Browse hierarchy | /browse/r/h | 3638
11 | Browse reference | /browse/r/r | 2441
12 | Browse other archives | /browse/r/h | 1890
13 | ShoppingBasket | /basket/ or checkout/ | 1820
14 | Discovery help | /help-with-your-research/discovery-help/ | 1542
15 | Paid search (1939 registers, home   guard, WO 416) | /paidsearch/ | 1531
16 | Browse creators | /browse/c | 1490
17 | Browse home | /browse/ | 1064
18 | Recordcopying | /pagecheck/ or recordcopying/ or   copyorder/ | 724
19 | Browse archives | /browse/a | 701
20 | My account | /account/ | 491
21 | Find an archive | /find-an-archive/ | 487
22 | Tags | /tags/browse or tags/details or   tags/index | 337
23 | Advanced orders | /order-documents-in-advance/ | 284
24 | Record creators filtered   search | /results/c | 248
25 | Record creators Search results | /results/c | 239
26 | Manor search | /manor-search/ or results/c or   results/r | 217
27 | Redirection | /redirection | 121
28 | download order | /account/yourorders | 113
29 | Redirection not found | /redirection/notfound | 81
30 | Search tagging | /taglist/searchtag | 24
31 | Record creators advanced search   results | /results/c | 21
32 | Bulk orders | /bulk-order-documents/ | 14
33 | Reader ticket regsitration | /reader-ticket/ | 7
