### ISSUE TITLE
Discovery help: content review/assessment

### ISSUE THREAD

**Issue by grange85** [nationalarchives/findability#16]
First draft at organising Discovery help.

* I need help with archives ([Start here](http://www.nationalarchives.gov.uk/help-with-your-research/start-here/))
* I need help with the catalogue ([Discovery help](http://www.nationalarchives.gov.uk/help-with-your-research/discovery-help/))
* I need help with my research ([Research guides](http://www.nationalarchives.gov.uk/help-with-your-research/#find-a-research-guide))

**Comment by jklepfer** [comment]
[DISCOVERY HELP TESTING INSIGHTS.docx](https://github.com/nationalarchives/findability/files/2387743/DISCOVERY.HELP.TESTING.INSIGHTS.docx)
[Notes from Workshop 4 September 2018.docx](https://github.com/nationalarchives/findability/files/2387745/Notes.from.Workshop.4.September.2018.docx)

**Comment by grange85** [comment]
I think this needs to be turned around to identify the problems?
