### ISSUE TITLE
Change the search box in Discovery to default to 'search Discovery'

### ISSUE THREAD

**Issue by grange85** [nationalarchives/findability#44]
## As a user, when I'm in Discovery I want the search box to default to 'search Discovery' and not 'search the website' so that I don't waste time clicking the wrong site search

- [x] Make the changes so that the search in the banner defaults to Discovery when a user is in Discovery
- [x] Deploy to TEST
- [ ] Confirm with Andrew C about deployment to LIVE (if this is stick behind Discovery 6)

**Comment by netdesignr** [comment]
Done
