### ISSUE TITLE
Put widget in research guides to collect feedback on what we could improve

### ISSUE THREAD

**Issue by cariannewhitworth** [nationalarchives/findability#65]
Create a widget to go across all 350+ research guides in Wordpress that presents the following questions to users (and tracks which guide they submit it from). 

Text:
Did you find the guidance you needed?
No = What did you expect to find? (Free text field? Plus character limit… 300?)
Yes = Any comments on your experience? (Free text field, plus character limit….300?)

Next text:
Thank you, we will use your feedback to improve our research guides.

**Comment by hoake** [comment]
The development plan for this issue is raised in Google Tag Manger scripts project
https://github.com/nationalarchives/tna-google-tag-manager-scripts/issues/42

**Comment by cariannewhitworth** [comment]
WIDGET TESTING
- [ ] Check guide is visible across a range of guides and all the buttons work on mobile and outside TNA.
- [ ] Check collected data includes research guide URL, yes/no, comments, and can be exported. 
- [ ] Receive and review feedback from CEE
- [ ] Make decision on box styling - to match Discovery or stay in keeping with Wordpress CSS?
- [ ] Make decision whether to change copy on ‘cancel’ button to something like ‘clear form’, or whether it’s more important to keep the cancel button and let people revert to the previous view? 
- [ ] Peer review the code.
- [ ] Plan comms for rest of organisation (CEE? Email on Narnia?)
- [ ] Write blog to introduce people to the widget.

**Comment by grange85** [comment]
Issue completed
