### ISSUE TITLE
SEO: Ensure that Discovery is configured to use Google Tag Manager

### ISSUE THREAD

**Issue by grange85** [nationalarchives/findability#8]
Make sure that Discovery is set up so that we can take full advantage of the benefits of Google Tag Manager (Indentifiy and plan enhanced GTM tracking).

- Tracking for custom searches via research guides
- All user interactions, searching, filters
- Extra information to identify pages

**Comment by grange85** [comment]
@netdesignr I see that there is some GTM code in Discovery (rather than old ga. code) - but might just be configured to log server side events? Could you update the issue with what specifically needs to be done in order to get a full and configurable GTM installation??

**Comment by hoake** [comment]
Sorry I just clicked on the wrong button, can this be re-opened?
